/**:
  controller_manager:
    ros__parameters:
      use_sim_time: False
      update_rate: 100  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      gripper_controller:
        type: position_controllers/GripperActionController

/**:
  gripper_controller:
    ros__parameters:
      joint: rh_r1
      allow_stalling: true
