# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - gripper_controller

  gripper_controller:
    type: GripperCommand
    action_ns: gripper_cmd
    joints:
      - rh_r1
